# Generated by Django 3.1.7 on 2021-04-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itme_description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_ame',
            new_name='item_name',
        ),
    ]
