# Generated by Django 3.1.7 on 2021-04-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210411_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
